# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e43f7b8cc6277494901d718706ee66c"
application_url = "https://tellenzi-laar.vercel.app/"
embedded = true
name = "tellenzi-laar"
handle = "tellenzi-laar"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://tellenzi-laar.vercel.app/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
